actor Child

boundary HomeScreen
boundary CategoryScreen
control CategoryViewModel
boundary GameScreen
== Navigating To The Game Screen ==

Child ->HomeScreen : selectCategory(): category
HomeScreen ->CategoryScreen: navigateTo(category)
CategoryScreen -> CategoryViewModel: getGames(ccategory)
CategoryViewModel --> CategoryScreen: List<Game>
CategoryScreen --> Child: Show game grid
Child ->CategoryScreen : selectGame() : gameId
CategoryScreen ->GameScreen : navigateTo(gameId)